name=puara-gestures
version=1.0.0
author=Edu_Meneses, SAT
maintainer=Edu <emeneses@sat.qc.ca>, SAT <innovation@sat.qc.ca>
sentence=high-level gesture recognition utilities and data filters 
paragraph=This library provides high-level gesture recognition utilities and data filters. It provides button/sensor managers and IMU-based gesture managers to implement gesture recognition. Included data filters preprocess sensor data to filter noise and control varying intensities for example. 
category=Data Processing
url=https://github.com/Puara/puara-gestures
architectures=*
