name: Build
on:
  push:

jobs:
  Desktop-OS-Tests:
    strategy:
      matrix:
        config:
          - {
              os: ubuntu-latest,
              cmake_options: "",
              dependencies: "sudo apt update -yqq && sudo apt -yqq install libboost-dev"
            }
          - {
              os: macos-latest,
              cmake_options: "CMAKE_PREFIX_PATH=/opt/homebrew",
              dependencies: "brew install boost eigen && brew link boost eigen"
            }
          - {
              os: windows-latest,
              cmake_options: "Boost_INCLUDE_DIR=D:/a/puara-gestures/puara-gestures/3rdparty",
              dependencies: "choco install eigen -y --no-progress"
            }

    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Dependencies
        run: ${{ matrix.config.dependencies }}

      - name: Configure
        run: |
          cmake -S tests -B build -DPUARA_GESTURES_ENABLE_STANDALONE=0 ${{ matrix.config.cmake_options }}

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Run Tests
        run: |
          cd build
          ctest -V -C Release

  Arduino-Compilation-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Update Arduino CLI core index
        run: |
          arduino-cli core update-index

      - name: Install Arduino cores
        run: |
          arduino-cli core install arduino:samd

      - name: Install required Arduino libraries
        run: |
          arduino-cli lib install "Eigen"
          arduino-cli lib install "boost-embedded-190"

      - name: Verify compilation for Arduino SAMD
        run: |
          arduino-cli compile -b arduino:samd:mzero tests/arduino/arduino_sketch_test/arduino_sketch_test.ino -v

  PlatformIO-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          pip install platformio

      - name: Install PlatformIO platforms and libraries
        run: |
          platformio lib install "Eigen"
          platformio lib install "boost-embedded-190"

      - name: Build PlatformIO project (generic Arduino SAMD)
        run: |
          cd tests/platformio
          platformio run -e samd
  