name: Build
on:
  push:

jobs:
  build-project:
    strategy:
      matrix:
        config:
          - {
              os: ubuntu-latest,
              cmake_options: "",
              dependencies: "echo 'ok'"
            }
          - {
              os: macos-latest,
              cmake_options: "CMAKE_PREFIX_PATH=/opt/homebrew",
              dependencies: "echo 'ok'"
            }
          - {
              os: windows-latest,
              cmake_options: "",
              dependencies: "echo ok"
            }

    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Dependencies
        run: ${{ matrix.config.dependencies }}

      - name: Build Project
        uses: threeal/cmake-action@v2.0.0
        with:
          options: |
            PUARA_GESTURES_ENABLE_STANDALONE=0
            ${{ matrix.config.cmake_options }}
